name: parental_care

channels:
  - conda-forge
  - defaults

dependencies:
  - python ==3.11
  - pip >=21.1
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - pandas
  - plotly
  - pytask >=0.2.3

  # Misc
  - black
  - ipython
  - jupyterlab
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  # Documentation
  - furo
  - myst-parser
  - nbsphinx
  - sphinx
  - sphinx-panels
  - sphinxcontrib-bibtex

  - pip:
    - kaleido
    - blackcellmagic

    # local installation
    - -e .
