channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >= 3.8
  - pip
  - setuptools_scm
  - toml

  # Documentation
  - furo
  - ipython
  - nbsphinx
  - myst-parser
  - sphinx
  - sphinx-autoapi
  - sphinx-copybutton
  - sphinx-panels

  - pip:
    - ../
    - sphinxext-opengraph
